// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lozeazpliiesvpwusmgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvemVhenBsaWllc3Zwd3VzbWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDEyNDgsImV4cCI6MjA2NjI3NzI0OH0.sCJfWKfVCnvwFjNQwjxSBTCo8zdvIq4_9ecVvdLYjn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);